# Generated by Django 5.1.2 on 2024-11-03 21:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafés',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=8)),
                ('setor', models.CharField(choices=[('hospital', 'Hospital'), ('hotel', 'Hotel'), ('hibrido', 'Híbrido'), ('lajes_corporativas', 'Lajes Corporativas'), ('logistica', 'Logística'), ('outros', 'Outros'), ('residencial', 'Residencial'), ('titulos_valores_mobiliarios', 'Títulos e Val. Mob.')], max_length=30)),
            ],
        ),
    ]
